name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push FastAPI Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: fastapi/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/embedding-api:fastapi-latest,${{ secrets.DOCKERHUB_USERNAME }}/embedding-api:fastapi-${{ github.sha }}

      - name: Build and push Triton Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: triton/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/embedding-api:triton-latest,${{ secrets.DOCKERHUB_USERNAME }}/embedding-api:triton-${{ github.sha }}
